services:
  mediainfo-bot:
    build: .
    container_name: mediainfo-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TMDB_API=${TMDB_API}
      - CHANNEL_ID=${CHANNEL_ID}
      - MY_CHAT_ID=${MY_CHAT_ID}
    env_file:
      - .env
    # networks:
    #   - bot-network
    # For webhook mode, uncomment the ports section
    # ports:
    #   - "8132:8000"

# Optional: Create a custom network
# networks:
#   bot-network:
#     driver: bridge
